#targets:
 # $default:
  #  builders:
   #   generators|annotations:
    #    enabled: true
   

builders:
  generators:
    target: ":generators"
    import: "package:generators/builder.dart"
    builder_factories: ["generateModel","generateEntity"]
    applies_builders: ["source_gen|combining_builder"]
    build_extensions: { ".dart": [".m.dart"] }
    auto_apply: dependents
    build_to: source

   
  